<?php
/**
 * @var $block \EBoost\StockAlert\Block\Catalog\Product\ListProduct
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
?>
<?php
$_productCollection = $block->getProductCollection();
$stockAlertHelper = $this->helper(\EBoost\StockAlert\Helper\Data::class);
echo $stockAlertHelper->renderStockStatus($_productCollection);